# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\RexZhann\nlp\PsyExtraction\ui\search.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 276)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 161, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.newCorpus = QtWidgets.QComboBox(self.layoutWidget)
        self.newCorpus.setDuplicatesEnabled(True)
        self.newCorpus.setObjectName("newCorpus")
        self.newCorpus.addItem("")

        self.verticalLayout.addWidget(self.newCorpus)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.uploadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.uploadButton.setObjectName("uploadButton")
        self.verticalLayout.addWidget(self.uploadButton)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 50, 172, 181))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.keyword = QtWidgets.QLineEdit(self.layoutWidget1)
        self.keyword.setObjectName("keyword")
        self.verticalLayout_2.addWidget(self.keyword)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.dep_key = QtWidgets.QComboBox(self.layoutWidget1)
        self.dep_key.setEditable(False)
        self.dep_key.setCurrentText("")
        self.dep_key.setObjectName("dep_key")
        self.dep_key.addItem("")
        self.dep_key.addItem("")
        self.dep_key.addItem("")
        self.verticalLayout_2.addWidget(self.dep_key)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.advanceButton = QtWidgets.QToolButton(self.layoutWidget1)
        self.advanceButton.setObjectName("advanceButton")
        self.verticalLayout_2.addWidget(self.advanceButton)
        self.searchButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout_2.addWidget(self.searchButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.newCorpus, self.uploadButton)
        Dialog.setTabOrder(self.uploadButton, self.keyword)
        Dialog.setTabOrder(self.keyword, self.dep_key)
        Dialog.setTabOrder(self.dep_key, self.advanceButton)
        Dialog.setTabOrder(self.advanceButton, self.searchButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "语料库选择"))
        self.newCorpus.setPlaceholderText(_translate("Dialog", "select the corpus"))
        self.newCorpus.setItemText(0, _translate("Dialog", "CLEAR"))
        self.uploadButton.setText(_translate("Dialog", "上传文件"))
        self.label_2.setText(_translate("Dialog", "搜索设置"))
        self.keyword.setPlaceholderText(_translate("Dialog", "输入关键词"))
        self.label_3.setText(_translate("Dialog", "选择依赖关系"))
        self.dep_key.setPlaceholderText(_translate("Dialog", "Select dependency factor"))
        self.dep_key.setItemText(0, _translate("Dialog", "complications"))
        self.dep_key.setItemText(1, _translate("Dialog", "diagnostic guidelines"))
        self.dep_key.setItemText(2, _translate("Dialog", "post conditions"))
        self.pushButton.setText(_translate("Dialog", "配置API"))
        self.advanceButton.setText(_translate("Dialog", "高级设置"))
        self.searchButton.setText(_translate("Dialog", "搜索"))
