# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\RexZhann\nlp\PsyExtraction\ui\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_setting(object):

    def __init__(self, main):
        self.main = main
        self.windowsize_value = 0
        self.topk_value = 0
        self.n_char_value = 0

    def setupUi(self, Dialog):

        

        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.label.setObjectName("label")
        self.windowsize = QtWidgets.QSpinBox(Dialog)
        self.windowsize.setGeometry(QtCore.QRect(180, 30, 41, 21))
        self.windowsize.setProperty("value", 5)
        self.windowsize.setObjectName("windowsize")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 111, 20))
        self.label_2.setObjectName("label_2")
        self.topk = QtWidgets.QSpinBox(Dialog)
        self.topk.setGeometry(QtCore.QRect(180, 80, 41, 20))
        self.topk.setProperty("value", 15)
        self.topk.setObjectName("topk")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 81, 18))
        self.label_3.setObjectName("label_3")
        self.n_char = QtWidgets.QSpinBox(Dialog)
        self.n_char.setGeometry(QtCore.QRect(180, 130, 41, 21))
        self.n_char.setProperty("value", 6)
        self.n_char.setObjectName("n_char")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.buttonBox.accepted.connect(self.save_settings)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "搜索窗口"))
        self.label_2.setText(_translate("Dialog", "聚类取样数量"))
        self.label_3.setText(_translate("Dialog", "维度数量"))

    def save_settings(self):
        self.windowsize_value = self.windowsize.value()
        self.topk_value = self.topk.value()
        self.n_char_value = self.n_char.value()


    def get_settings(self):
        return self.windowsize_value, self.topk_value, self.n_char_value
        
